---
kind: pipeline
type: docker

steps:
  - name: build
    image: elixir:1.9
    commands:
      - mix do local.hex --force, local.rebar --force
      - MIX_ENV=prod mix do deps.get --only $MIX_ENV, deps.compile
      - MIX_ENV=prod mix release
  - name: release
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      repo: registry.ubu-002.km8.es/renttoday-phoenix
      registry: registry.ubu-002.km8.es
      username:
        from_secret: docker_repo_user
      password:
        from_secret: docker_repo_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: web-01.km8.es
      port: 22
      username:
        from_secret: web-01_ssh_user
      key:
        from_secret: web-01_ssh_key
      passphrase:
        from_secret: web-01_ssh_passphrase
      script:
        - cd /srv/docker/renttoday-phoenix
        - docker-compose down
        - docker-compose pull
        - docker-compose up -d
